// clientes/livros-angular/src/app/livro-dados/livro-dados.component.ts
import { Component } from '@angular/core';
import { CommonModule } from '@angular/common';
import { Router } from '@angular/router';
import { Editora } from '../editora';
import { Livro } from '../livro';
import { ControleEditoraService } from '../controle-editora.service';
import { ControleLivrosService } from '../controle-livros.service';
import { FormsModule } from '@angular/forms';

@Component({
  selector: 'app-livro-dados',
  standalone: true,
  imports: [CommonModule, FormsModule],
  templateUrl: './livro-dados.component.html',
  styleUrls: ['./livro-dados.component.css'],
})
export class LivroDadosComponent {
  public livro: Livro = new Livro('', 0, '0', '0,0', ['0']);
  public autoresForm: string = '';
  public editoras: Editora[] = [];

  private servEditora: ControleEditoraService;
  private servLivros: ControleLivrosService;
  private router: Router;

  constructor() {
    this.servEditora = new ControleEditoraService();
    this.servLivros = new ControleLivrosService();
    this.router = new Router();
  }

  ngOnInit() {
    this.editoras = this.servEditora.getEditoras();
  }

  incluir = () => {
    this.livro.autores = this.autoresForm.split('\n');
    this.servLivros
      .incluir(this.livro)
      .then(() => this.router.navigateByUrl('/livros'));
  };
}

<main class="main">
  <h1>Incluir Livro</h1>
  <form (submit)="incluir()" ngNativeValidate>
    <div class="form-group">
      <label for="titulo">Título</label>
      <input
        type="text"
        id="titulo"
        [(ngModel)]="livro.titulo"
        name="titulo"
        required
        class="form-control"
      />
    </div>
    <div class="form-group">
      <label for="resumo">Resumo</label>
      <textarea
        id="resumo"
        [(ngModel)]="livro.resumo"
        name="resumo"
        class="form-control"
      ></textarea>
    </div>
    <div class="form-group">
      <label for="editora">Editora</label>
      <select
        id="editora"
        [(ngModel)]="livro.codEditora"
        name="codEditora"
        required
        class="form-control"
      >
        <option *ngFor="let editora of editoras" [value]="editora.codEditora">
          {{ editora.nome }}
        </option>
      </select>
    </div>
    <div class="form-group">
      <label for="autores">Autores</label>
      <textarea
        id="autores"
        [(ngModel)]="autoresForm"
        name="autoresForm"
        class="form-control"
      ></textarea>
    </div>
    <button type="submit" class="btn btn-primary">Incluir</button>
  </form>
</main>

// clientes/livros-next/src/componentes/LivroDados.tsx
'use client';

import ControleEditora from '@/classes/controle/ControleEditora';
import ControleLivros from '@/classes/controle/ControleLivros';
import Livro from '@/classes/modelo/Livro';
import { useRouter } from 'next/navigation';
import React from 'react';

export default function LivroDados() {
	const controleLivros = new ControleLivros();
	const controleEditora = new ControleEditora();

	const opcoes = controleEditora
		.getEditoras()
		.map((editora) => ({ value: editora.codEditora, text: editora.nome }));

	const [titulo, setTitulo] = React.useState('');
	const [resumo, setResumo] = React.useState('');
	const [autores, setAutores] = React.useState('');
	const [codEditora, setCodEditora] = React.useState(opcoes[0].value);

	const navigate = useRouter();

	function incluirLivro(livro: Livro) {
		controleLivros.incluir(livro).then(() => navigate.push('/'));
	}

	function tratarCombo(evento: any) {
		setCodEditora(+evento.target.value);
	}

	function incluir(event: any) {
		event.preventDefault();

		incluirLivro(
			new Livro(
				titulo,
				resumo,
				autores.split(`,`).map((text) => text.trim()),
				codEditora
			)
		);
	}

	return (
		<main className='container'>
			<h1 className='mb-4'>Adicionar livro</h1>
			<form onSubmit={incluir}>
				<div className='mb-3'>
					<label className='form-label'>Titulo</label>
					<input
						required
						value={titulo}
						onChange={(e) => setTitulo(e.target.value)}
						className='form-control'
					/>
				</div>
				<div className='mb-3'>
					<label className='form-label'>Resumo</label>
					<input
						required
						value={resumo}
						onChange={(e) => setResumo(e.target.value)}
						className='form-control'
					/>
				</div>
				<div className='mb-3'>
					<label className='form-label'>Autores</label>
					<input
						required
						value={autores}
						onChange={(e) => setAutores(e.target.value)}
						className='form-control'
					/>
				</div>
				<div className='mb-3'>
					<label className='form-label'>Editoras</label>
					<select onChange={tratarCombo} className='form-select'>
						{opcoes.map((opcao, index) => (
							<option key={index} value={opcao.value}>
								{opcao.text}
							</option>
						))}
					</select>
				</div>
				<button className='btn btn-primary'>Enviar</button>
			</form>
		</main>
	);
}
